Traceback (most recent call last):
  File "/home/pi/.romill/single_rml_2.py", line 3, in <module>
    getdata(2)
  File "/home/pi/.romill/romill.py", line 77, in getdata
    mount = mount_rml(device_number)
  File "/home/pi/.romill/romill.py", line 113, in mount_rml
    device_path = cfg["devices"][rml_id]['dir']
KeyError: 2

